### ISSUE TITLE
build toolchain for linux host machines

### ISSUE THREAD

**Issue by michaelknoch** [vgorloff/swift-everywhere-toolchain#115]
Do you know of any major blockers that are keeping us from building an android toolchain which can be used on linux host machines? Did you ever try? If you think this is something the project can benefit from i would like to take a look at. @vgorloff

**Comment by vgorloff** [comment]
Maybe this repo would be interesting for you https://github.com/buttaface/swift-android-sdk.
It is a Toolchain for building Swift for Android on Android ([Termux](https://termux.com))

Or maybe this - https://github.com/readdle/swift-android-toolchain

I had in past Linux builders (via Vagrant), but deprecated and removed them due slow compilation process on a virtual linux box :0

I would rather make Cross compilation for Linux and Windows from macOS than fighting against virtual linux instances.

btw: Probably ofiicial Swift git repo buildable for Android on Linux. It had received some build scripts improvements since last 2 years.

**Comment by michaelknoch** [comment]
> I would rather make Cross compilation for Linux and Windows from macOS than fighting against virtual linux instances.

Am I understanding you correctly, with Cross compilation for Linux from macOS you mean building a toolchain which can be used on linux but built on macOS?

**Comment by vgorloff** [comment]
Not really. The toolchain build on macOS machine and which can be used only on macOS machine, but it should be able to generate binaries for Android, Windows, Linux.

**Comment by vgorloff** [comment]
Closing issue as the official Swift build scripts and/or Termux build routines is trying solve the problem of building Swift toolchain for Android usable on Linux OS.
